version: '3'
services:
  web:
    image: chupurnov/ymaps3-test-server:latest
    tty: true
    working_dir: /opt/server
    env_file:
      - .env
    ports:
      - '8080:8080'

    depends_on:
      - db

  db:
    # To work with search by coordinates
    image: postgis/postgis:15-3.4-alpine
    env_file:
      - .env
    volumes:
      - ./compose/data/dump/:/docker-entrypoint-initdb.d
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    env_file:
      - .env

    ports:
      - '8999:80'
    restart: no
